name: Build & migrate to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase
        uses: supabase/setup-cli@v1
        with:
          version: "2.53.6"

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_PROD }}

      - name: Push changes to Supabase
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_PROD }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Connect Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run EAS production build
        run: eas build --profile production --platform android --non-interactive --no-wait
